/* ============================================================
   MJ Vinylsamling — album-database
   Alle LP-udgivelser hvor Michael Jackson har medvirket.
   `wiki` er sidens titel på engelsk Wikipedia — bruges til at
   hente coverbilledet automatisk (se js/covers.js).
   ============================================================ */

const CATEGORIES = {
  studie:     { label: "Solo-studiealbum", emoji: "🎤", color: "#e8b93c" },
  jackson5:   { label: "Jackson 5",        emoji: "✋", color: "#e0653a" },
  jacksons:   { label: "The Jacksons",     emoji: "👨‍👦‍👦", color: "#4fa3d1" },
  soundtrack: { label: "Soundtracks",      emoji: "🎬", color: "#8f6fd1" },
  opsamling:  { label: "Opsamlinger",      emoji: "💿", color: "#5bbd8b" },
  special:    { label: "Særudgivelser",    emoji: "✨", color: "#d15b9e" },
};

const ALBUMS = [
  /* ---------- Solo-studiealbum ---------- */
  { id: "got-to-be-there", title: "Got to Be There", artist: "Michael Jackson", year: 1972, category: "studie", label: "Motown",
    wiki: "Got to Be There",
    desc: "Michaels allerførste soloalbum — han var kun 13 år, da det udkom!" },
  { id: "ben", title: "Ben", artist: "Michael Jackson", year: 1972, category: "studie", label: "Motown",
    wiki: "Ben (album)",
    desc: "Titelsangen om rotten Ben blev Michaels første nummer 1-hit som solist." },
  { id: "music-and-me", title: "Music & Me", artist: "Michael Jackson", year: 1973, category: "studie", label: "Motown",
    wiki: "Music & Me",
    desc: "Et blødt og fint album — på coveret sidder Michael med en akustisk guitar." },
  { id: "forever-michael", title: "Forever, Michael", artist: "Michael Jackson", year: 1975, category: "studie", label: "Motown",
    wiki: "Forever, Michael",
    desc: "Michaels sidste studiealbum for Motown, med hittet \"Just a Little Bit of You\"." },
  { id: "off-the-wall", title: "Off the Wall", artist: "Michael Jackson", year: 1979, category: "studie", label: "Epic",
    wiki: "Off the Wall (album)",
    desc: "Det første album med Quincy Jones — disco-mesterværket der gjorde Michael til superstjerne." },
  { id: "thriller", title: "Thriller", artist: "Michael Jackson", year: 1982, category: "studie", label: "Epic",
    wiki: "Thriller (album)", rare: false,
    desc: "Verdens bedst sælgende album nogensinde! Beat It, Billie Jean, Thriller — hit efter hit." },
  { id: "bad", title: "Bad", artist: "Michael Jackson", year: 1987, category: "studie", label: "Epic",
    wiki: "Bad (album)",
    desc: "Fem singler fra samme album gik nummer 1 i USA — det var aldrig sket før." },
  { id: "dangerous", title: "Dangerous", artist: "Michael Jackson", year: 1991, category: "studie", label: "Epic",
    wiki: "Dangerous (Michael Jackson album)",
    desc: "Med det vilde, detaljerede cover malet af kunstneren Mark Ryden. \"Black or White\" og \"Remember the Time\"." },
  { id: "history", title: "HIStory: Past, Present and Future, Book I", artist: "Michael Jackson", year: 1995, category: "studie", label: "Epic",
    wiki: "HIStory",
    desc: "Kæmpe dobbeltalbum: én plade med hits og én med helt nye sange som \"Earth Song\"." },
  { id: "invincible", title: "Invincible", artist: "Michael Jackson", year: 2001, category: "studie", label: "Epic",
    wiki: "Invincible (Michael Jackson album)",
    desc: "Michaels sidste studiealbum — udkom med cover i fem forskellige farver. Kan du samle dem alle?" },
  { id: "michael", title: "Michael", artist: "Michael Jackson", year: 2010, category: "studie", label: "Epic",
    wiki: "Michael (album)",
    desc: "Det første album udgivet efter Michaels død, med sangen \"Hold My Hand\" sammen med Akon." },
  { id: "xscape", title: "Xscape", artist: "Michael Jackson", year: 2014, category: "studie", label: "Epic",
    wiki: "Xscape (album)",
    desc: "\"Love Never Felt So Good\" med Justin Timberlake blev et kæmpehit — 32 år efter den blev indspillet." },

  /* ---------- Jackson 5 ---------- */
  { id: "diana-ross-presents", title: "Diana Ross Presents the Jackson 5", artist: "The Jackson 5", year: 1969, category: "jackson5", label: "Motown",
    wiki: "Diana Ross Presents the Jackson 5",
    desc: "Debutalbummet! Med \"I Want You Back\" — Michael var bare 11 år." },
  { id: "abc", title: "ABC", artist: "The Jackson 5", year: 1970, category: "jackson5", label: "Motown",
    wiki: "ABC (The Jackson 5 album)",
    desc: "\"ABC\" og \"The Love You Save\" skubbede begge The Beatles ned fra førstepladsen." },
  { id: "third-album", title: "Third Album", artist: "The Jackson 5", year: 1970, category: "jackson5", label: "Motown",
    wiki: "Third Album",
    desc: "Med den smukke ballade \"I'll Be There\" — deres fjerde nummer 1-hit i træk." },
  { id: "christmas-album", title: "Jackson 5 Christmas Album", artist: "The Jackson 5", year: 1970, category: "jackson5", label: "Motown",
    wiki: "Jackson 5 Christmas Album",
    desc: "Julealbummet med \"Santa Claus Is Comin' to Town\" — perfekt til december!" },
  { id: "maybe-tomorrow", title: "Maybe Tomorrow", artist: "The Jackson 5", year: 1971, category: "jackson5", label: "Motown",
    wiki: "Maybe Tomorrow (The Jackson 5 album)",
    desc: "Med \"Never Can Say Goodbye\" — en af gruppens allersmukkeste sange." },
  { id: "goin-back-to-indiana", title: "Goin' Back to Indiana", artist: "The Jackson 5", year: 1971, category: "jackson5", label: "Motown",
    wiki: "Goin' Back to Indiana",
    desc: "Soundtrack til deres eget tv-show — hjem til Indiana, hvor det hele startede." },
  { id: "lookin-through-the-windows", title: "Lookin' Through the Windows", artist: "The Jackson 5", year: 1972, category: "jackson5", label: "Motown",
    wiki: "Lookin' Through the Windows",
    desc: "Brødrene begyndte at lyde mere voksne — med den flotte titelsang." },
  { id: "skywriter", title: "Skywriter", artist: "The Jackson 5", year: 1973, category: "jackson5", label: "Motown",
    wiki: "Skywriter",
    desc: "Med et flyvemaskine-cover! Indeholder hittet \"Hallelujah Day\"." },
  { id: "git-get-it-together", title: "G.I.T.: Get It Together", artist: "The Jackson 5", year: 1973, category: "jackson5", label: "Motown",
    wiki: "G.I.T.: Get It Together",
    desc: "Funky og psykedelisk — med \"Dancing Machine\", hvor Michael lavede robot-dansen på tv." },
  { id: "dancing-machine", title: "Dancing Machine", artist: "The Jackson 5", year: 1974, category: "jackson5", label: "Motown",
    wiki: "Dancing Machine (album)",
    desc: "Opkaldt efter kæmpehittet — Jackson 5 i fuld disco-fart." },
  { id: "moving-violation", title: "Moving Violation", artist: "The Jackson 5", year: 1975, category: "jackson5", label: "Motown",
    wiki: "Moving Violation",
    desc: "Det sidste rigtige studiealbum som \"Jackson 5\", inden de skiftede navn og pladeselskab." },
  { id: "joyful-jukebox-music", title: "Joyful Jukebox Music", artist: "The Jackson 5", year: 1976, category: "jackson5", label: "Motown", rare: true,
    wiki: "Joyful Jukebox Music",
    desc: "Udgivet af Motown efter brødrene var rejst — svær at finde og et rigtigt samlerfund!" },
  { id: "boogie", title: "Boogie", artist: "The Jacksons 5", year: 1979, category: "jackson5", label: "Motown", rare: true,
    wiki: "Boogie (album)",
    desc: "En af de allersjældneste Jackson-plader overhovedet — kun få eksemplarer blev solgt. Den ultimative jagt!" },
  { id: "greatest-hits-j5", title: "Greatest Hits", artist: "The Jackson 5", year: 1971, category: "jackson5", label: "Motown",
    wiki: "Greatest Hits (Jackson 5 album)",
    desc: "Den første store hit-samling — alle de tidlige klassikere på én plade." },
  { id: "in-japan", title: "In Japan!", artist: "The Jackson 5", year: 1973, category: "jackson5", label: "Motown", rare: true,
    wiki: "In Japan!",
    desc: "Livealbum fra Japan — udkom oprindeligt kun i Japan og er et sjældent samlerobjekt." },

  /* ---------- The Jacksons ---------- */
  { id: "the-jacksons", title: "The Jacksons", artist: "The Jacksons", year: 1976, category: "jacksons", label: "Epic",
    wiki: "The Jacksons (album)",
    desc: "Nyt navn, nyt pladeselskab — med discohittet \"Enjoy Yourself\"." },
  { id: "goin-places", title: "Goin' Places", artist: "The Jacksons", year: 1977, category: "jacksons", label: "Epic",
    wiki: "Goin' Places (The Jacksons album)",
    desc: "Med ballonfærd på coveret — lavet sammen med soul-legenderne Gamble & Huff." },
  { id: "destiny", title: "Destiny", artist: "The Jacksons", year: 1978, category: "jacksons", label: "Epic",
    wiki: "Destiny (The Jacksons album)",
    desc: "Brødrene skrev selv sangene — med \"Blame It on the Boogie\" og \"Shake Your Body\"." },
  { id: "triumph", title: "Triumph", artist: "The Jacksons", year: 1980, category: "jacksons", label: "Epic",
    wiki: "Triumph (The Jacksons album)",
    desc: "\"Can You Feel It\" åbner albummet — en af gruppens mest episke sange." },
  { id: "the-jacksons-live", title: "The Jacksons Live!", artist: "The Jacksons", year: 1981, category: "jacksons", label: "Epic",
    wiki: "The Jacksons Live!",
    desc: "Dobbelt-livealbum fra Triumph-turnéen — hør publikum skrige til \"Don't Stop 'Til You Get Enough\"." },
  { id: "victory", title: "Victory", artist: "The Jacksons", year: 1984, category: "jacksons", label: "Epic",
    wiki: "Victory (The Jacksons album)",
    desc: "Alle seks brødre samlet — med \"State of Shock\", hvor Michael synger duet med Mick Jagger." },
  { id: "2300-jackson-street", title: "2300 Jackson Street", artist: "The Jacksons", year: 1989, category: "jacksons", label: "Epic",
    wiki: "2300 Jackson Street",
    desc: "Opkaldt efter barndomshjemmets adresse. Michael er med på titelsangen sammen med hele familien." },

  /* ---------- Soundtracks ---------- */
  { id: "the-wiz", title: "The Wiz", artist: "Diverse (med Michael Jackson)", year: 1978, category: "soundtrack", label: "MCA",
    wiki: "The Wiz (soundtrack)",
    desc: "Fra filmen hvor Michael spiller Fugleskræmslet — \"Ease on Down the Road\" med Diana Ross." },
  { id: "et-storybook", title: "E.T. the Extra-Terrestrial", artist: "Michael Jackson", year: 1982, category: "soundtrack", label: "MCA", rare: true,
    wiki: "E.T. the Extra-Terrestrial (soundtrack)",
    desc: "Michael fortæller historien om E.T. og synger \"Someone in the Dark\". Blev trukket tilbage — meget sjælden!" },
  { id: "this-is-it", title: "This Is It", artist: "Michael Jackson", year: 2009, category: "soundtrack", label: "Epic",
    wiki: "This Is It (Michael Jackson album)",
    desc: "Musikken fra filmen om Michaels sidste koncertforberedelser — med den usungne titelsang." },

  /* ---------- Opsamlinger ---------- */
  { id: "best-of-mj", title: "The Best of Michael Jackson", artist: "Michael Jackson", year: 1975, category: "opsamling", label: "Motown",
    wiki: "The Best of Michael Jackson",
    desc: "Den første solo-opsamling — alle de tidlige Motown-hits samlet." },
  { id: "anthology", title: "Anthology", artist: "Michael Jackson", year: 1976, category: "opsamling", label: "Motown",
    wiki: "Anthology (Michael Jackson album)",
    desc: "Stor 3-LP-boks med de bedste Motown-år — flot i reolen!" },
  { id: "one-day-in-your-life", title: "One Day in Your Life", artist: "Michael Jackson", year: 1981, category: "opsamling", label: "Motown",
    wiki: "One Day in Your Life (album)",
    desc: "Motown udgav den, da Michael var blevet kæmpestjerne — titelsangen gik nummer 1 i England." },
  { id: "18-greatest-hits", title: "18 Greatest Hits", artist: "Michael Jackson & The Jackson 5", year: 1983, category: "opsamling", label: "Telstar",
    wiki: "18 Greatest Hits",
    desc: "Lå nummer 1 i England i hele 3 uger midt i Thriller-feberen i 1983." },
  { id: "essential", title: "The Essential Michael Jackson", artist: "Michael Jackson", year: 2005, category: "opsamling", label: "Epic",
    wiki: "The Essential Michael Jackson",
    desc: "Hele karrieren på én udgivelse — fra \"I Want You Back\" til \"You Rock My World\"." },
  { id: "scream", title: "Scream", artist: "Michael Jackson", year: 2017, category: "opsamling", label: "Epic",
    wiki: "Scream (Michael Jackson album)",
    desc: "Halloween-samling med de uhyggelige hits — vinyludgaven selvlyser i mørke!" },

  /* ---------- Særudgivelser ---------- */
  { id: "blood-on-the-dance-floor", title: "Blood on the Dance Floor: HIStory in the Mix", artist: "Michael Jackson", year: 1997, category: "special", label: "Epic",
    wiki: "Blood on the Dance Floor: HIStory in the Mix",
    desc: "Verdens bedst sælgende remixalbum — med fem helt nye sange, bl.a. \"Blood on the Dance Floor\"." },
  { id: "farewell-my-summer-love", title: "Farewell My Summer Love", artist: "Michael Jackson", year: 1984, category: "special", label: "Motown",
    wiki: "Farewell My Summer Love",
    desc: "Gamle, glemte optagelser fra 1973, som Motown fandt i arkivet og udgav under Thriller-feberen." },
  { id: "looking-back-to-yesterday", title: "Looking Back to Yesterday", artist: "Michael Jackson", year: 1986, category: "special", label: "Motown", rare: true,
    wiki: "Looking Back to Yesterday",
    desc: "Endnu en skattekiste af uudgivne Motown-optagelser — svær at støve op i dag." },
  { id: "original-soul", title: "The Original Soul of Michael Jackson", artist: "Michael Jackson", year: 1987, category: "special", label: "Motown",
    wiki: "The Original Soul of Michael Jackson",
    desc: "Motowns svar på Bad — de bedste tidlige soul-numre i nyt udvalg." },
  { id: "thriller-25", title: "Thriller 25", artist: "Michael Jackson", year: 2008, category: "special", label: "Epic",
    wiki: "Thriller 25",
    desc: "Jubilæumsudgaven med nye duetter — bl.a. \"The Girl Is Mine 2008\" med will.i.am." },
  { id: "bad-25", title: "Bad 25", artist: "Michael Jackson", year: 2012, category: "special", label: "Epic",
    wiki: "Bad 25",
    desc: "Stor jubilæumsboks med demoer og ikke tidligere udgivne sange fra Bad-tiden." },
];

/* ============================================================
   Milepæle (badges) — det motiverende lag!
   `test(stats)` afgør om badgen er optjent.
   `progress(stats)` returnerer [nu, mål] til statuslinjen.
   ============================================================ */

const ACHIEVEMENTS = [
  { id: "first", emoji: "🎉", title: "Den første plade!",
    desc: "Føj din allerførste LP til samlingen.",
    progress: s => [Math.min(s.owned, 1), 1] },
  { id: "five", emoji: "🌟", title: "Godt i gang",
    desc: "Saml 5 plader.",
    progress: s => [Math.min(s.owned, 5), 5] },
  { id: "ten", emoji: "💿", title: "Rigtig samler",
    desc: "Saml 10 plader.",
    progress: s => [Math.min(s.owned, 10), 10] },
  { id: "twentyfive", emoji: "🕺", title: "Superfan",
    desc: "Saml 25 plader.",
    progress: s => [Math.min(s.owned, 25), 25] },
  { id: "half", emoji: "🚀", title: "Halvvejs!",
    desc: "Ej halvdelen af alle plader på listen.",
    progress: s => [s.owned, Math.ceil(s.total / 2)] },
  { id: "complete", emoji: "🏆", title: "Komplet samling!",
    desc: "Ej ALLE plader på listen. Vildt!",
    progress: s => [s.owned, s.total] },
  { id: "thrillernight", emoji: "🧟", title: "Thriller Night",
    desc: "Ej verdens bedst sælgende album: Thriller.",
    needsAlbums: ["thriller"] },
  { id: "kingofpop", emoji: "👑", title: "King of Pop",
    desc: "Ej de fire store: Off the Wall, Thriller, Bad og Dangerous.",
    needsAlbums: ["off-the-wall", "thriller", "bad", "dangerous"] },
  { id: "glove", emoji: "🧤", title: "Den hvide handske",
    desc: "Ej alle 12 solo-studiealbum.",
    needsCategory: "studie" },
  { id: "motownstar", emoji: "✋", title: "Motown-stjerne",
    desc: "Saml 5 Jackson 5-plader.",
    progress: s => [Math.min(s.byCategory.jackson5 || 0, 5), 5] },
  { id: "motownmaster", emoji: "🎩", title: "Motown-mester",
    desc: "Ej alle Jackson 5-plader.",
    needsCategory: "jackson5" },
  { id: "familyband", emoji: "👨‍👦‍👦", title: "Familiebandet",
    desc: "Ej alle plader af The Jacksons.",
    needsCategory: "jacksons" },
  { id: "seventies", emoji: "🪩", title: "70'er-fan",
    desc: "Saml 10 plader fra 1970'erne.",
    progress: s => [Math.min(s.byDecade[1970] || 0, 10), 10] },
  { id: "eighties", emoji: "📼", title: "80'er-ikon",
    desc: "Saml 5 plader fra 1980'erne.",
    progress: s => [Math.min(s.byDecade[1980] || 0, 5), 5] },
  { id: "treasure", emoji: "🗺️", title: "Skattejæger",
    desc: "Find en af de sjældne plader (markeret med ✨).",
    test: s => s.rareOwned >= 1,
    progress: s => [Math.min(s.rareOwned, 1), 1] },
  { id: "moonwalker", emoji: "🌙", title: "Moonwalker",
    desc: "Find 3 sjældne plader. Du er en ægte pladejæger!",
    progress: s => [Math.min(s.rareOwned, 3), 3] },
  { id: "wishmaker", emoji: "⭐", title: "Ønskejagten",
    desc: "Giv 3 plader ønske-stjerner, så du ved, hvad du jagter.",
    progress: s => [Math.min(s.wishlisted, 3), 3] },
  { id: "dream", emoji: "💭", title: "Drømmepladen",
    desc: "Markér en plade med ⭐⭐⭐ — dit allerhøjeste ønske.",
    progress: s => [Math.min(s.dreamMarked, 1), 1] },
  { id: "notes", emoji: "✍️", title: "Pladenørden",
    desc: "Skriv en note på en af dine plader — fx hvor du fandt den.",
    progress: s => [Math.min(s.withNotes, 1), 1] },
];
