/* ============================================================
   MJ Vinylsamling — album-database
   Alle LP-udgivelser hvor Michael Jackson har medvirket.
   `wiki` er sidens titel på engelsk Wikipedia — bruges til at
   hente coverbilledet automatisk (se js/covers.js).
   ============================================================ */

const CATEGORIES = {
  studie:     { label: "Solo-studiealbum", emoji: "🎤", color: "#e8b93c" },
  jackson5:   { label: "Jackson 5",        emoji: "✋", color: "#e0653a" },
  jacksons:   { label: "The Jacksons",     emoji: "👨‍👦‍👦", color: "#4fa3d1" },
  soundtrack: { label: "Soundtracks",      emoji: "🎬", color: "#8f6fd1" },
  opsamling:  { label: "Opsamlinger",      emoji: "💿", color: "#5bbd8b" },
  special:    { label: "Særudgivelser",    emoji: "✨", color: "#d15b9e" },
};

const ALBUMS = [
  /* ---------- Solo-studiealbum ---------- */
  { id: "got-to-be-there", title: "Got to Be There", artist: "Michael Jackson", year: 1972, category: "studie", label: "Motown",
    wiki: "Got to Be There",
    desc: "Michaels allerførste soloalbum — han var kun 13 år, da det udkom!" },
  { id: "ben", title: "Ben", artist: "Michael Jackson", year: 1972, category: "studie", label: "Motown",
    wiki: "Ben (album)",
    desc: "Titelsangen om rotten Ben blev Michaels første nummer 1-hit som solist." },
  { id: "music-and-me", title: "Music & Me", artist: "Michael Jackson", year: 1973, category: "studie", label: "Motown",
    wiki: "Music & Me",
    desc: "Et blødt og fint album — på coveret sidder Michael med en akustisk guitar." },
  { id: "forever-michael", title: "Forever, Michael", artist: "Michael Jackson", year: 1975, category: "studie", label: "Motown",
    wiki: "Forever, Michael",
    desc: "Michaels sidste studiealbum for Motown, med hittet \"Just a Little Bit of You\"." },
  { id: "off-the-wall", title: "Off the Wall", artist: "Michael Jackson", year: 1979, category: "studie", label: "Epic",
    wiki: "Off the Wall (album)",
    desc: "Det første album med Quincy Jones — disco-mesterværket der gjorde Michael til superstjerne." },
  { id: "thriller", title: "Thriller", artist: "Michael Jackson", year: 1982, category: "studie", label: "Epic",
    wiki: "Thriller (album)", rare: false,
    desc: "Verdens bedst sælgende album nogensinde! Beat It, Billie Jean, Thriller — hit efter hit." },
  { id: "bad", title: "Bad", artist: "Michael Jackson", year: 1987, category: "studie", label: "Epic",
    wiki: "Bad (album)",
    desc: "Fem singler fra samme album gik nummer 1 i USA — det var aldrig sket før." },
  { id: "dangerous", title: "Dangerous", artist: "Michael Jackson", year: 1991, category: "studie", label: "Epic",
    wiki: "Dangerous (Michael Jackson album)",
    desc: "Med det vilde, detaljerede cover malet af kunstneren Mark Ryden. \"Black or White\" og \"Remember the Time\"." },
  { id: "history", title: "HIStory: Past, Present and Future, Book I", artist: "Michael Jackson", year: 1995, category: "studie", label: "Epic",
    wiki: "HIStory",
    desc: "Kæmpe dobbeltalbum: én plade med hits og én med helt nye sange som \"Earth Song\"." },
  { id: "invincible", title: "Invincible", artist: "Michael Jackson", year: 2001, category: "studie", label: "Epic",
    wiki: "Invincible (Michael Jackson album)",
    desc: "Michaels sidste studiealbum — udkom med cover i fem forskellige farver. Kan du samle dem alle?" },
  { id: "michael", title: "Michael", artist: "Michael Jackson", year: 2010, category: "studie", label: "Epic",
    wiki: "Michael (album)",
    desc: "Det første album udgivet efter Michaels død, med sangen \"Hold My Hand\" sammen med Akon." },
  { id: "xscape", title: "Xscape", artist: "Michael Jackson", year: 2014, category: "studie", label: "Epic",
    wiki: "Xscape (album)",
    desc: "\"Love Never Felt So Good\" med Justin Timberlake blev et kæmpehit — 32 år efter den blev indspillet." },

  /* ---------- Jackson 5 ---------- */
  { id: "diana-ross-presents", title: "Diana Ross Presents the Jackson 5", artist: "The Jackson 5", year: 1969, category: "jackson5", label: "Motown",
    wiki: "Diana Ross Presents the Jackson 5",
    desc: "Debutalbummet! Med \"I Want You Back\" — Michael var bare 11 år." },
  { id: "abc", title: "ABC", artist: "The Jackson 5", year: 1970, category: "jackson5", label: "Motown",
    wiki: "ABC (The Jackson 5 album)",
    desc: "\"ABC\" og \"The Love You Save\" skubbede begge The Beatles ned fra førstepladsen." },
  { id: "third-album", title: "Third Album", artist: "The Jackson 5", year: 1970, category: "jackson5", label: "Motown",
    wiki: "Third Album",
    desc: "Med den smukke ballade \"I'll Be There\" — deres fjerde nummer 1-hit i træk." },
  { id: "christmas-album", title: "Jackson 5 Christmas Album", artist: "The Jackson 5", year: 1970, category: "jackson5", label: "Motown",
    wiki: "Jackson 5 Christmas Album",
    desc: "Julealbummet med \"Santa Claus Is Comin' to Town\" — perfekt til december!" },
  { id: "maybe-tomorrow", title: "Maybe Tomorrow", artist: "The Jackson 5", year: 1971, category: "jackson5", label: "Motown",
    wiki: "Maybe Tomorrow (The Jackson 5 album)",
    desc: "Med \"Never Can Say Goodbye\" — en af gruppens allersmukkeste sange." },
  { id: "goin-back-to-indiana", title: "Goin' Back to Indiana", artist: "The Jackson 5", year: 1971, category: "jackson5", label: "Motown",
    wiki: "Goin' Back to Indiana",
    desc: "Soundtrack til deres eget tv-show — hjem til Indiana, hvor det hele startede." },
  { id: "lookin-through-the-windows", title: "Lookin' Through the Windows", artist: "The Jackson 5", year: 1972, category: "jackson5", label: "Motown",
    wiki: "Lookin' Through the Windows",
    desc: "Brødrene begyndte at lyde mere voksne — med den flotte titelsang." },
  { id: "skywriter", title: "Skywriter", artist: "The Jackson 5", year: 1973, category: "jackson5", label: "Motown",
    wiki: "Skywriter",
    desc: "Med et flyvemaskine-cover! Indeholder hittet \"Hallelujah Day\"." },
  { id: "git-get-it-together", title: "G.I.T.: Get It Together", artist: "The Jackson 5", year: 1973, category: "jackson5", label: "Motown",
    wiki: "G.I.T.: Get It Together",
    desc: "Funky og psykedelisk — med \"Dancing Machine\", hvor Michael lavede robot-dansen på tv." },
  { id: "dancing-machine", title: "Dancing Machine", artist: "The Jackson 5", year: 1974, category: "jackson5", label: "Motown",
    wiki: "Dancing Machine (album)",
    desc: "Opkaldt efter kæmpehittet — Jackson 5 i fuld disco-fart." },
  { id: "moving-violation", title: "Moving Violation", artist: "The Jackson 5", year: 1975, category: "jackson5", label: "Motown",
    wiki: "Moving Violation",
    desc: "Det sidste rigtige studiealbum som \"Jackson 5\", inden de skiftede navn og pladeselskab." },
  { id: "joyful-jukebox-music", title: "Joyful Jukebox Music", artist: "The Jackson 5", year: 1976, category: "jackson5", label: "Motown", rare: true,
    wiki: "Joyful Jukebox Music",
    desc: "Udgivet af Motown efter brødrene var rejst — svær at finde og et rigtigt samlerfund!" },
  { id: "boogie", title: "Boogie", artist: "The Jacksons 5", year: 1979, category: "jackson5", label: "Motown", rare: true,
    wiki: "Boogie (album)",
    desc: "En af de allersjældneste Jackson-plader overhovedet — kun få eksemplarer blev solgt. Den ultimative jagt!" },
  { id: "greatest-hits-j5", title: "Greatest Hits", artist: "The Jackson 5", year: 1971, category: "jackson5", label: "Motown",
    wiki: "Greatest Hits (Jackson 5 album)",
    desc: "Den første store hit-samling — alle de tidlige klassikere på én plade." },
  { id: "in-japan", title: "In Japan!", artist: "The Jackson 5", year: 1973, category: "jackson5", label: "Motown", rare: true,
    wiki: "In Japan!",
    desc: "Livealbum fra Japan — udkom oprindeligt kun i Japan og er et sjældent samlerobjekt." },

  /* ---------- The Jacksons ---------- */
  { id: "the-jacksons", title: "The Jacksons", artist: "The Jacksons", year: 1976, category: "jacksons", label: "Epic",
    wiki: "The Jacksons (album)",
    desc: "Nyt navn, nyt pladeselskab — med discohittet \"Enjoy Yourself\"." },
  { id: "goin-places", title: "Goin' Places", artist: "The Jacksons", year: 1977, category: "jacksons", label: "Epic",
    wiki: "Goin' Places (The Jacksons album)",
    desc: "Med ballonfærd på coveret — lavet sammen med soul-legenderne Gamble & Huff." },
  { id: "destiny", title: "Destiny", artist: "The Jacksons", year: 1978, category: "jacksons", label: "Epic",
    wiki: "Destiny (The Jacksons album)",
    desc: "Brødrene skrev selv sangene — med \"Blame It on the Boogie\" og \"Shake Your Body\"." },
  { id: "triumph", title: "Triumph", artist: "The Jacksons", year: 1980, category: "jacksons", label: "Epic",
    wiki: "Triumph (The Jacksons album)",
    desc: "\"Can You Feel It\" åbner albummet — en af gruppens mest episke sange." },
  { id: "the-jacksons-live", title: "The Jacksons Live!", artist: "The Jacksons", year: 1981, category: "jacksons", label: "Epic",
    wiki: "The Jacksons Live!",
    desc: "Dobbelt-livealbum fra Triumph-turnéen — hør publikum skrige til \"Don't Stop 'Til You Get Enough\"." },
  { id: "victory", title: "Victory", artist: "The Jacksons", year: 1984, category: "jacksons", label: "Epic",
    wiki: "Victory (The Jacksons album)",
    desc: "Alle seks brødre samlet — med \"State of Shock\", hvor Michael synger duet med Mick Jagger." },
  { id: "2300-jackson-street", title: "2300 Jackson Street", artist: "The Jacksons", year: 1989, category: "jacksons", label: "Epic",
    wiki: "2300 Jackson Street",
    desc: "Opkaldt efter barndomshjemmets adresse. Michael er med på titelsangen sammen med hele familien." },

  /* ---------- Soundtracks ---------- */
  { id: "the-wiz", title: "The Wiz", artist: "Diverse (med Michael Jackson)", year: 1978, category: "soundtrack", label: "MCA",
    wiki: "The Wiz (soundtrack)",
    desc: "Fra filmen hvor Michael spiller Fugleskræmslet — \"Ease on Down the Road\" med Diana Ross." },
  { id: "et-storybook", title: "E.T. the Extra-Terrestrial", artist: "Michael Jackson", year: 1982, category: "soundtrack", label: "MCA", rare: true,
    wiki: "E.T. the Extra-Terrestrial (soundtrack)",
    desc: "Michael fortæller historien om E.T. og synger \"Someone in the Dark\". Blev trukket tilbage — meget sjælden!" },
  { id: "this-is-it", title: "This Is It", artist: "Michael Jackson", year: 2009, category: "soundtrack", label: "Epic",
    wiki: "This Is It (Michael Jackson album)",
    desc: "Musikken fra filmen om Michaels sidste koncertforberedelser — med den usungne titelsang." },

  /* ---------- Opsamlinger ---------- */
  { id: "best-of-mj", title: "The Best of Michael Jackson", artist: "Michael Jackson", year: 1975, category: "opsamling", label: "Motown",
    wiki: "The Best of Michael Jackson",
    desc: "Den første solo-opsamling — alle de tidlige Motown-hits samlet." },
  { id: "anthology", title: "Anthology", artist: "Michael Jackson", year: 1976, category: "opsamling", label: "Motown",
    wiki: "Anthology (Michael Jackson album)",
    desc: "Stor 3-LP-boks med de bedste Motown-år — flot i reolen!" },
  { id: "one-day-in-your-life", title: "One Day in Your Life", artist: "Michael Jackson", year: 1981, category: "opsamling", label: "Motown",
    wiki: "One Day in Your Life (album)",
    desc: "Motown udgav den, da Michael var blevet kæmpestjerne — titelsangen gik nummer 1 i England." },
  { id: "18-greatest-hits", title: "18 Greatest Hits", artist: "Michael Jackson & The Jackson 5", year: 1983, category: "opsamling", label: "Telstar",
    wiki: "18 Greatest Hits",
    desc: "Lå nummer 1 i England i hele 3 uger midt i Thriller-feberen i 1983." },
  { id: "essential", title: "The Essential Michael Jackson", artist: "Michael Jackson", year: 2005, category: "opsamling", label: "Epic",
    wiki: "The Essential Michael Jackson",
    desc: "Hele karrieren på én udgivelse — fra \"I Want You Back\" til \"You Rock My World\"." },
  { id: "scream", title: "Scream", artist: "Michael Jackson", year: 2017, category: "opsamling", label: "Epic",
    wiki: "Scream (Michael Jackson album)",
    desc: "Halloween-samling med de uhyggelige hits — vinyludgaven selvlyser i mørke!" },

  /* ---------- Særudgivelser ---------- */
  { id: "blood-on-the-dance-floor", title: "Blood on the Dance Floor: HIStory in the Mix", artist: "Michael Jackson", year: 1997, category: "special", label: "Epic",
    wiki: "Blood on the Dance Floor: HIStory in the Mix",
    desc: "Verdens bedst sælgende remixalbum — med fem helt nye sange, bl.a. \"Blood on the Dance Floor\"." },
  { id: "farewell-my-summer-love", title: "Farewell My Summer Love", artist: "Michael Jackson", year: 1984, category: "special", label: "Motown",
    wiki: "Farewell My Summer Love",
    desc: "Gamle, glemte optagelser fra 1973, som Motown fandt i arkivet og udgav under Thriller-feberen." },
  { id: "looking-back-to-yesterday", title: "Looking Back to Yesterday", artist: "Michael Jackson", year: 1986, category: "special", label: "Motown", rare: true,
    wiki: "Looking Back to Yesterday",
    desc: "Endnu en skattekiste af uudgivne Motown-optagelser — svær at støve op i dag." },
  { id: "original-soul", title: "The Original Soul of Michael Jackson", artist: "Michael Jackson", year: 1987, category: "special", label: "Motown",
    wiki: "The Original Soul of Michael Jackson",
    desc: "Motowns svar på Bad — de bedste tidlige soul-numre i nyt udvalg." },
  { id: "thriller-25", title: "Thriller 25", artist: "Michael Jackson", year: 2008, category: "special", label: "Epic",
    wiki: "Thriller 25",
    desc: "Jubilæumsudgaven med nye duetter — bl.a. \"The Girl Is Mine 2008\" med will.i.am." },
  { id: "bad-25", title: "Bad 25", artist: "Michael Jackson", year: 2012, category: "special", label: "Epic",
    wiki: "Bad 25",
    desc: "Stor jubilæumsboks med demoer og ikke tidligere udgivne sange fra Bad-tiden." },
];

/* ============================================================
   Samler-niveauer — jo flere plader, jo sejere titel!
   ============================================================ */

const LEVELS = [
  { min: 0,  emoji: "🎧", title: "Ny i klubben" },
  { min: 1,  emoji: "🌱", title: "Pladespirer" },
  { min: 5,  emoji: "💿", title: "Vinyl-ven" },
  { min: 10, emoji: "🎶", title: "Rigtig samler" },
  { min: 15, emoji: "🕺", title: "Moonwalker i træning" },
  { min: 20, emoji: "🧟", title: "Thriller-jæger" },
  { min: 30, emoji: "🎩", title: "Vinyl-mester" },
  { min: 40, emoji: "🌟", title: "Levende legende" },
  { min: 49, emoji: "👑", title: "KING OF POP" },
];

/* Michaels livsfase, da pladen udkom (født 29. august 1958) */
function mjPhase(year) {
  if (year <= 1970) return "barn";   // 11-12 år
  if (year <= 1977) return "teen";   // 13-19 år
  if (year <= 1989) return "ung";    // 20-31 år — verdensstjernen
  if (year <= 2001) return "konge";  // 32-43 år — King of Pop
  return "evig";                     // arven — for evigt ung
}

const PHASE_LABELS = {
  barn: "Barnestjernen (11-12 år)",
  teen: "Teenageren (13-19 år)",
  ung: "Verdensstjernen (20'erne)",
  konge: "King of Pop (30'erne og 40'erne)",
  evig: "For evigt ung (arven)",
};

/* ============================================================
   Milepæle (badges) — det motiverende lag!
   `test(stats)` afgør om badgen er optjent.
   `progress(stats)` returnerer [nu, mål] til statuslinjen.
   `group` styrer, hvilken sektion badgen vises i.
   ============================================================ */

const ACHIEVEMENT_GROUPS = {
  samling: "📀 Samlingen vokser",
  rejse: "🎂 Michaels rejse",
  trofae: "🏆 Store trofæer",
  tema: "🎨 Temajagt",
  flid: "✍️ Flid og kærlighed",
};

const ACHIEVEMENTS = [
  /* --- 📀 Samlingen vokser --- */
  { id: "first", group: "samling", emoji: "🎉", title: "Den første plade!",
    desc: "Føj din allerførste LP til samlingen.",
    progress: s => [Math.min(s.owned, 1), 1] },
  { id: "five", group: "samling", emoji: "🌟", title: "Godt i gang",
    desc: "Saml 5 plader.",
    progress: s => [Math.min(s.owned, 5), 5] },
  { id: "ten", group: "samling", emoji: "💿", title: "Rigtig samler",
    desc: "Saml 10 plader.",
    progress: s => [Math.min(s.owned, 10), 10] },
  { id: "twentyfive", group: "samling", emoji: "🕺", title: "Superfan",
    desc: "Saml 25 plader.",
    progress: s => [Math.min(s.owned, 25), 25] },
  { id: "half", group: "samling", emoji: "🚀", title: "Halvvejs!",
    desc: "Ej halvdelen af alle plader på listen.",
    progress: s => [s.owned, Math.ceil(s.total / 2)] },
  { id: "complete", group: "samling", emoji: "🏆", title: "Komplet samling!",
    desc: "Ej ALLE plader på listen. Vildt!",
    progress: s => [s.owned, s.total] },

  /* --- 🎂 Michaels rejse (hans alder på pladerne) --- */
  { id: "thirteen", group: "rejse", emoji: "🎤", title: "13 år og verdensstjerne",
    desc: "Ej Got to Be There — Michaels første soloalbum, indspillet da han var 13.",
    needsAlbums: ["got-to-be-there"] },
  { id: "origin", group: "rejse", emoji: "🌱", title: "Hvor det hele begyndte",
    desc: "Ej debutpladen Diana Ross Presents the Jackson 5 fra 1969 — Michael var 11 år!",
    needsAlbums: ["diana-ross-presents"] },
  { id: "lilmichael", group: "rejse", emoji: "👦", title: "Lille Michael",
    desc: "Ej en plade fra før Michael fyldte 13 (1969-1970).",
    progress: s => [Math.min(s.phases.barn || 0, 1), 1] },
  { id: "teenidol", group: "rejse", emoji: "🕶️", title: "Teen-idol",
    desc: "Saml 3 plader fra Michaels teenageår (1971-1977).",
    progress: s => [Math.min(s.phases.teen || 0, 3), 3] },
  { id: "lifejourney", group: "rejse", emoji: "🎂", title: "Hele rejsen",
    desc: "Ej mindst én plade fra hver af Michaels fem livsfaser — fra barnestjerne til for evigt ung.",
    progress: s => [s.phasesCovered, 5] },
  { id: "decademaster", group: "rejse", emoji: "🗓️", title: "Årti-mesteren",
    desc: "Ej mindst én plade fra hvert årti: 60'erne, 70'erne, 80'erne, 90'erne, 00'erne og 10'erne.",
    progress: s => [s.decadesOwned, 6] },

  /* --- 🏆 Store trofæer --- */
  { id: "thrillernight", group: "trofae", emoji: "🧟", title: "Thriller Night",
    desc: "Ej verdens bedst sælgende album: Thriller.",
    needsAlbums: ["thriller"] },
  { id: "kingofpop", group: "trofae", emoji: "👑", title: "King of Pop",
    desc: "Ej de fire store: Off the Wall, Thriller, Bad og Dangerous.",
    needsAlbums: ["off-the-wall", "thriller", "bad", "dangerous"] },
  { id: "glove", group: "trofae", emoji: "🧤", title: "Den hvide handske",
    desc: "Ej alle 12 solo-studiealbum.",
    needsCategory: "studie" },
  { id: "motownstar", group: "trofae", emoji: "✋", title: "Motown-stjerne",
    desc: "Saml 5 Jackson 5-plader.",
    progress: s => [Math.min(s.byCategory.jackson5 || 0, 5), 5] },
  { id: "motownmaster", group: "trofae", emoji: "🎩", title: "Motown-mester",
    desc: "Ej alle Jackson 5-plader.",
    needsCategory: "jackson5" },
  { id: "familyband", group: "trofae", emoji: "👨‍👦‍👦", title: "Familiebandet",
    desc: "Ej alle plader af The Jacksons.",
    needsCategory: "jacksons" },
  { id: "moviestar", group: "trofae", emoji: "🎬", title: "Filmstjernen",
    desc: "Ej alle soundtracks — The Wiz, E.T. og This Is It.",
    needsCategory: "soundtrack" },
  { id: "anthologist", group: "trofae", emoji: "📚", title: "Opsamleren",
    desc: "Ej alle opsamlingsplader.",
    needsCategory: "opsamling" },
  { id: "specialist", group: "trofae", emoji: "✨", title: "Specialisten",
    desc: "Ej alle særudgivelser — remixer, jubilæer og skjulte skatte.",
    needsCategory: "special" },
  { id: "treasure", group: "trofae", emoji: "🗺️", title: "Skattejæger",
    desc: "Find en af de sjældne plader (markeret med ✨).",
    progress: s => [Math.min(s.rareOwned, 1), 1] },
  { id: "moonwalker", group: "trofae", emoji: "🌙", title: "Moonwalker",
    desc: "Find 3 sjældne plader. Du er en ægte pladejæger!",
    progress: s => [Math.min(s.rareOwned, 3), 3] },

  /* --- 🎨 Temajagt (ord og temaer der går igen) --- */
  { id: "dancefloor", group: "tema", emoji: "🪩", title: "Dansegulvet",
    desc: "Ej begge plader med dans i titlen: Dancing Machine og Blood on the Dance Floor.",
    needsAlbums: ["dancing-machine", "blood-on-the-dance-floor"] },
  { id: "wildfriends", group: "tema", emoji: "🐀", title: "Vilde venner",
    desc: "Ej Ben (om en rotte) og E.T. (om en rumven) — Michaels to mest usædvanlige venskaber.",
    needsAlbums: ["ben", "et-storybook"] },
  { id: "xmas", group: "tema", emoji: "🎄", title: "Jackson-jul",
    desc: "Ej Jackson 5 Christmas Album — december bliver aldrig det samme igen.",
    needsAlbums: ["christmas-album"] },
  { id: "livewire", group: "tema", emoji: "🎸", title: "Live og direkte",
    desc: "Ej begge livealbum: The Jacksons Live! og In Japan!",
    needsAlbums: ["the-jacksons-live", "in-japan"] },
  { id: "seventies", group: "tema", emoji: "🕰️", title: "70'er-fan",
    desc: "Saml 10 plader fra 1970'erne.",
    progress: s => [Math.min(s.byDecade[1970] || 0, 10), 10] },
  { id: "eighties", group: "tema", emoji: "📼", title: "80'er-ikon",
    desc: "Saml 5 plader fra 1980'erne.",
    progress: s => [Math.min(s.byDecade[1980] || 0, 5), 5] },
  { id: "nineties", group: "tema", emoji: "📟", title: "90'er-holdet",
    desc: "Ej alle plader fra 1990'erne.",
    progress: s => [s.byDecade[1990] || 0, s.decadeTotals[1990] || 0] },

  /* --- ✍️ Flid og kærlighed (brug siden!) --- */
  { id: "wishmaker", group: "flid", emoji: "⭐", title: "Ønskejagten",
    desc: "Giv 3 plader ønske-stjerner, så du ved, hvad du jagter.",
    progress: s => [Math.min(s.wishlisted, 3), 3] },
  { id: "wish10", group: "flid", emoji: "🌠", title: "Ønskebrønden",
    desc: "Hav 10 plader på ønskelisten på samme tid.",
    progress: s => [Math.min(s.wishlisted, 10), 10] },
  { id: "dream", group: "flid", emoji: "💭", title: "Drømmepladen",
    desc: "Markér en plade med ⭐⭐⭐ — dit allerhøjeste ønske.",
    progress: s => [Math.min(s.dreamMarked, 1), 1] },
  { id: "notes", group: "flid", emoji: "✍️", title: "Pladenørden",
    desc: "Skriv en bemærkning på en plade — fx hvor du fandt den, eller hvor du har set den til salg.",
    progress: s => [Math.min(s.withNotes, 1), 1] },
  { id: "notes5", group: "flid", emoji: "📖", title: "Historiefortælleren",
    desc: "Skriv bemærkninger på 5 plader.",
    progress: s => [Math.min(s.withNotes, 5), 5] },
  { id: "notes15", group: "flid", emoji: "📚", title: "Pladebibliotekaren",
    desc: "Skriv bemærkninger på 15 plader — en hel dagbog om samlingen!",
    progress: s => [Math.min(s.withNotes, 15), 15] },
  { id: "archivist", group: "flid", emoji: "🗃️", title: "Arkivaren",
    desc: "Udfyld stand på 5 af dine plader.",
    progress: s => [Math.min(s.withCondition, 5), 5] },
  { id: "photographer", group: "flid", emoji: "📸", title: "Fotografen",
    desc: "Sæt dit eget billede på en plade — fx et foto af netop dit eksemplar.",
    progress: s => [Math.min(s.withOwnCover, 1), 1] },
  { id: "visitor5", group: "flid", emoji: "📅", title: "Fast gæst",
    desc: "Brug siden på 5 forskellige dage.",
    progress: s => [Math.min(s.activeDays, 5), 5] },
  { id: "visitor15", group: "flid", emoji: "🪑", title: "Stamgæst",
    desc: "Brug siden på 15 forskellige dage.",
    progress: s => [Math.min(s.activeDays, 15), 15] },
  { id: "visitor30", group: "flid", emoji: "🏠", title: "Klubhuset",
    desc: "Brug siden på 30 forskellige dage — det her er DIT sted.",
    progress: s => [Math.min(s.activeDays, 30), 30] },
  { id: "streak3", group: "flid", emoji: "🔥", title: "Varm streak",
    desc: "Besøg siden 3 dage i træk.",
    progress: s => [Math.min(s.streak, 3), 3] },
  { id: "streak7", group: "flid", emoji: "🌋", title: "Brandvarm!",
    desc: "Besøg siden 7 dage i træk — Michael ville være stolt.",
    progress: s => [Math.min(s.streak, 7), 7] },
];
